version: '3.8'

services:
  api:
    build: .
    container_name: library-api
    ports:
      - "8000:8000"
    depends_on:
      - library_db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  library_db:
    image: postgres:15
    container_name: library_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: library-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data: