"""removed author role

Revision ID: 2863919bd916
Revises: d48cbab6fc85
Create Date: 2025-04-21 14:09:41.858431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2863919bd916'
down_revision: Union[str, None] = 'd48cbab6fc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_authors', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_authors', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
