"""added request model

Revision ID: 446446a0b077
Revises: 2863919bd916
Create Date: 2025-04-21 18:11:33.880503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '446446a0b077'
down_revision: Union[str, None] = '2863919bd916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_book_status_date', table_name='book_request_queue')
    op.drop_index('ix_book_request_queue_request_id', table_name='book_request_queue')
    op.drop_table('book_request_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_request_queue',
    sa.Column('request_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notification_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='book_request_queue_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='book_request_queue_user_id_fkey'),
    sa.PrimaryKeyConstraint('request_id', name='book_request_queue_pkey')
    )
    op.create_index('ix_book_request_queue_request_id', 'book_request_queue', ['request_id'], unique=False)
    op.create_index('idx_book_status_date', 'book_request_queue', ['book_id', 'status', 'request_date'], unique=False)
    # ### end Alembic commands ###
